services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: >
      sh -c "sleep 15 && npm run start:dev api-gateway"
    depends_on:
      - auth-users
      - kino-db
      - rabbitmq
      - db
      - db2
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    env_file:
      - ./apps/api-gateway/.env
    environment:
      - NODE_ENV=development
      - JWT_EXPIRES_IN=124h
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:5173
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - USERS_QUEUE=users_queue
      - FILMS_QUEUE=films_queue
      - COMMENTS_QUEUE=comments_queue
      - PRIVATE_KEY=${PRIVATE_KEY:-your-super-secret-jwt-key-here}
    networks:
      - default
    restart: unless-stopped
  auth-users:
    build:
      context: .
      dockerfile: ./apps/auth-users/Dockerfile
      target: development
    command: >
      sh -c "sleep 15 && npm run start:dev auth-users"
    environment:
      - PORT=3001
      - POSTGRES_HOST=db2
      - POSTGRES_USER=root
      - POSTGRES_DB=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
      - PRIVATE_KEY=${PRIVATE_KEY:-your-super-secret-jwt-key-here}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-124h}
    depends_on:
      - db2
      - rabbitmq
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: unless-stopped
  kino-db:
    build:
      context: .
      dockerfile: ./apps/kino-db/Dockerfile
      target: development
    command: >
      sh -c "sleep 15 && npm run start:dev kino-db"
    ports:
      - '3002:3002'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kino
      - PRIVATE_KEY=${PRIVATE_KEY:-your-super-secret-jwt-key-here}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-124h}
    depends_on:
      - auth-users
      - db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - default
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    restart: unless-stopped   
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kino
    ports:
      - 5432:5432 
    volumes:   
    - ./devops/kino-db/final-kino-initial-data-dump.sql:/docker-entrypoint-initdb.d/final-kino-initial-data-dump.sql
    networks:
      - default
    restart: unless-stopped  
  db2:
    container_name: db2
    image: postgres:15.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user
    ports:
      - 5433:5432
    volumes:   
    - ./devops/users-db/users-init-dump.sql:/docker-entrypoint-initdb.d/users-init-dump.sql
    networks:
      - default
    restart: unless-stopped  
